version: "3"
services:
  develop:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1::8888"
    volumes:
      - ../:/mnt
    command: bash -c "cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash"
    stdin_open: true
    container_name: "mgta415_fp_robo_advisor"
    tty: true
    env_file:
      - ../.env
